# Generated by Django 2.1.4 on 2019-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(blank=True, max_length=21)),
                ('construction_object_name', models.CharField(blank=True, max_length=50)),
                ('construction_objects', models.FileField(blank=True, upload_to='BuildObjects')),
                ('construction_image', models.ImageField(blank=True, upload_to='Image/Objects image')),
                ('descriptions', models.TextField(verbose_name='Текстовое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(blank=True, max_length=20)),
                ('map_image', models.ImageField(blank=True, upload_to='Image/Maps')),
            ],
        ),
    ]
